import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("접근성에 필요한 문서 구조와 대체 입력을 제공한다", async () => {
  const [page, layout, css] = await Promise.all([
    readFile(new URL("app/page.tsx", root), "utf8"),
    readFile(new URL("app/layout.tsx", root), "utf8"),
    readFile(new URL("app/globals.css", root), "utf8"),
  ]);

  assert.match(layout, /<html lang="ko">/);
  assert.match(page, /href="#main-content"/);
  assert.match(page, /id="main-content"/);
  assert.match(page, /role="progressbar"/);
  assert.match(page, /aria-valuenow=/);
  assert.match(page, /aria-live="polite"/);
  assert.match(page, /aria-describedby="drawing-help"/);
  assert.match(page, /<label htmlFor="text-hint">/);
  assert.match(page, /<textarea id="text-hint"/);
  assert.match(page, /id="drawer-answer"/);
  assert.match(page, /const \[drawerAnswer, setDrawerAnswer\]/);
  assert.match(page, /const \[choiceOptions, setChoiceOptions\]/);
  assert.match(page, /question\.suggestions/);
  assert.match(page, /const drawerPlayer = demoCouple\[quizIndex % 2\]/);
  assert.match(page, /const guesserPlayer = demoCouple\[\(quizIndex \+ 1\) % 2\]/);
  assert.match(page, /Math\.floor\(quizIndex \/ 2\) \+ 1/);
  assert.match(page, /Math\.round\(\(score \/ quizQuestions\.length\) \* 100\)/);
  assert.match(page, /const burgerOrders/);
  assert.match(page, /"burger-intro" \| "burger-play" \| "burger-result"/);
  assert.match(page, /screen\.startsWith\("burger-"\)/);
  assert.match(page, /title: "달콤한 주방"/);
  assert.match(page, /setBurgerTime\(\(time\) =>/);
  assert.match(page, /aria-label="현재 쌓은 햄버거"/);
  assert.match(page, /type KitchenOrder/);
  assert.match(page, /const sideInfo:/);
  assert.match(page, /setBurgerRoleIndex\(Math\.random\(\) < 0\.5 \? 0 : 1\)/);
  assert.match(page, /aria-label="대기 중인 메뉴판"/);
  assert.match(page, /role="status"><span>✓<\/span><b>주문 통과!/);
  assert.match(page, /currentOrder\.sides\.includes\(side\)/);
  assert.match(page, /\| "final-result"/);
  assert.match(page, /title: "우리가 주인공"/);
  assert.match(page, /musicRound === "roundFive"/);
  assert.match(page, /"sawtooth"/);
  assert.match(page, /const medalInfo =/);
  assert.match(page, /🥇/);
  assert.match(page, /🥈/);
  assert.match(page, /🥉/);
  assert.match(page, /"final-choice-first"/);
  assert.match(page, /"final-choice-second"/);
  assert.match(page, /"final-reveal"/);
  assert.match(page, /"private-chat"/);
  assert.match(page, /title: "둘만의 고요한 밤"/);
  assert.match(page, /aria-label="대화 내용"/);
  assert.match(page, /htmlFor="chat-message"/);
  assert.match(page, /데모 메시지와 사진은 서버로 전송되지 않으며/);
  assert.match(page, /const \[chatSeconds, setChatSeconds\] = useState\(3600\)/);
  assert.match(page, /Math\.max\(0, seconds - 1\)/);
  assert.match(page, /대화 종료/);
  assert.match(page, /const \[friendStatus, setFriendStatus\]/);
  assert.match(page, /500 마일리지로 대화 신청/);
  assert.match(page, /setMileageBalance\(\(balance\) => balance - 500\)/);
  assert.match(page, /aria-label=\{`내 마일리지 \$\{mileageBalance\}`\}/);
  assert.match(page, /결제 정책 준비 중/);
  assert.match(page, /const demoFriendPlayers =/);
  assert.match(page, /aria-label="내 친구 3명"/);
  assert.match(page, /setPendingChatFriendId\(friendId\)/);
  assert.match(page, /role="dialog" aria-modal="true"/);
  assert.match(page, /채팅하기를 원합니다/);
  assert.match(page, /참여하시겠습니까/);
  assert.match(page, /setMileageBalance\(\(balance\) => balance \+ 250\)/);
  assert.match(page, /거절하면 신청자에게 250 마일리지가 반환됩니다/);
  assert.match(page, /const \[chatEndedBy, setChatEndedBy\]/);
  assert.match(page, /님이 대화를 종료했습니다/);
  assert.match(page, /onClick=\{endPrivateChat\}>대화 종료/);
  assert.match(page, /채팅방 나가기/);
  assert.match(page, /disabled=\{chatSeconds === 0 \|\| chatEndedBy !== null\}/);
  assert.match(page, /const finalRanking =/);
  assert.match(page, /aria-label="최종 커플 순위"/);
  assert.match(page, /각자 <b>\{mileage\} 마일리지/);
  assert.match(page, /최종 결과 보기/);
  assert.match(page, /disabled=\{!drawerAnswer\.trim\(\)\}/);
  assert.match(page, /disabled=\{!textHint\.trim\(\)\}/);
  assert.doesNotMatch(page, /question\.answer/);
  assert.match(page, /canvas\.toDataURL\("image\/png"\)/);
  assert.match(page, /src=\{drawingImage\}/);
  assert.match(page, /aria-pressed=\{musicStarted && !isMuted\}/);
  assert.match(page, /setIsMuted/);
  assert.match(page, /const musicThemes:/);
  assert.match(page, /title: "첫눈에"/);
  assert.match(page, /title: "우리의 대화"/);
  assert.match(page, /title: "마음의 온도"/);
  assert.match(page, /const compatibilityQuestions/);
  assert.match(page, /aria-label="상황 궁합 진행률"/);
  assert.match(page, /첫 번째 사람의 답은 안전하게 숨겨졌어요/);
  assert.match(page, /playVoice\(melodyNote \* 2/);
  assert.match(page, /playVoice\(chord\[0\] \/ 2/);
  assert.match(page, /aria-label="볼륨 줄이기"/);
  assert.match(page, /aria-label="볼륨 키우기"/);
  assert.match(page, /Math\.max\(10, level - 10\)/);
  assert.match(page, /Math\.min\(100, level \+ 10\)/);
  assert.match(page, /role="status"/);
  assert.match(page, /둘만의 다음 장면으로 걸어가는 중/);
  assert.match(page, /aria-busy=\{isTransitioning\}/);
  assert.match(page, /\| "login" \| "signup" \| "profile" \| "verify" \| "lobby" \| "create-room" \| "waiting-room"/);
  assert.match(page, /useState<Screen>\("login"\)/);
  assert.match(page, /id="login-email"/);
  assert.match(page, /id="signup-nickname"/);
  assert.match(page, /휴대전화 본인인증 데모/);
  assert.match(page, /인증 없이 로비 둘러보기/);
  assert.match(page, /if \(!isVerified\)/);
  assert.match(page, /aria-label="현재 로비 현황"/);
  assert.match(page, /\$\{room\.capacity\}명 중 \$\{room\.people\}명 참가/);
  assert.match(page, /주민등록번호 · 인증 문자 · 연락처 공개값/);
  assert.match(page, /id="profile-photo"/);
  assert.match(page, /type="file" multiple/);
  assert.match(page, /profilePhotos\.length \+ files\.length > 3/);
  assert.match(page, /makePrimaryProfilePhoto/);
  assert.match(page, /removeProfilePhoto/);
  assert.match(page, /대표로 선택/);
  assert.match(page, /const \[primaryProfilePhotoIndex, setPrimaryProfilePhotoIndex\]/);
  assert.match(page, /aria-pressed=\{index === primaryProfilePhotoIndex\}/);
  assert.match(page, /setPrimaryProfilePhotoIndex\(index\)/);
  assert.match(page, /id="profile-name"/);
  assert.match(page, /id="profile-age"/);
  assert.match(page, /id="profile-region"/);
  assert.match(page, /id="profile-job"/);
  assert.match(page, /id="profile-intro"/);
  assert.match(page, /id="chat-image"/);
  assert.match(page, /previewChatImage/);
  assert.match(page, /message\.image/);
  assert.match(page, /\(!chatInput\.trim\(\) && !chatImage\)/);
  assert.match(page, /file\.size > 5 \* 1024 \* 1024/);
  assert.match(page, /aria-label="성별로 구분된 대기 중인 참가자 프로필"/);
  assert.match(page, /aria-pressed=\{isReady\}/);
  assert.match(page, /모든 참가자가 모이면 자동으로 게임을 시작합니다/);
  assert.match(page, /type RoomConfig =/);
  assert.match(page, /id="room-title"/);
  assert.match(page, /id="room-min-age"/);
  assert.match(page, /id="room-max-age"/);
  assert.match(page, /event\.target\.value\.replace\(\/\^0\+\(\?=\\d\)\/, ""\)/);
  assert.match(page, /id="room-region"/);
  assert.match(page, /role="radiogroup" aria-label="참여 인원"/);
  assert.match(page, /role="radiogroup" aria-label="방 테마"/);
  assert.match(page, /const roomThemes =/);
  assert.match(page, /setRoomTheme\(theme\.label\)/);
  assert.match(page, /tag: `\$\{roomThemes\.find/);
  assert.match(page, /남녀 비율은 언제나 1:1로 유지됩니다/);
  assert.match(page, /setCreatedRoom\(room\)/);
  assert.match(page, /activeRoom\.capacity - activeRoom\.people/);
  assert.match(page, /id="profile-gender"/);
  assert.match(page, /남성 참가자/);
  assert.match(page, /여성 참가자/);
  assert.match(page, /const \[likedProfiles, setLikedProfiles\]/);
  assert.match(page, /aria-pressed=\{likedProfiles\.includes\(person\.id\)\}/);
  assert.match(page, /받은 좋아요 \$\{receivedLikes\}개/);
  assert.match(page, /웃어요.*슬퍼요.*화났어요.*지루해요/s);
  assert.match(page, /대기실에서는 채팅 없이 간단한 이모티콘만 보낼 수 있어요/);
  assert.match(page, /const waitingReactions =/);
  assert.match(page, /profileReactionBubble/);
  assert.match(page, /내 조건에 맞는 방 찾기/);
  assert.match(page, /filteredLobbyRooms\.slice/);
  assert.match(page, /aria-label="게임방 목록 페이지"/);
  assert.match(page, /profileReadyState/);
  assert.match(page, /강퇴 투표/);
  assert.match(page, /kickVoteThreshold/);
  assert.match(page, /openProfilePhotos\(person\.id\)/);
  assert.match(page, /200 마일리지로 열기/);
  assert.match(page, /setMileageBalance\(\(balance\) => balance - 200\)/);
  assert.match(page, /unlockedPhotoIds/);
  assert.match(css, /:focus-visible/);
  assert.match(css, /prefers-reduced-motion:\s*reduce/);
  assert.match(css, /forced-colors:\s*active/);
});

test("지원 브라우저 범위를 명시한다", async () => {
  const packageJson = JSON.parse(await readFile(new URL("package.json", root), "utf8"));
  assert.deepEqual(packageJson.browserslist, [
    "last 2 Chrome versions",
    "last 2 Edge versions",
    "last 2 Firefox versions",
    "last 2 Safari versions",
    "not dead",
  ]);
});
